swagger: '2.0'
info:
  version: "0.0.0"
  title: Test - Should contain URI scheme

host: localhost

schemes:
  - http
  - https

basePath: /api

paths:
  /test:
    get:
      responses:
        200:
          description: OK
          schema:
            type: string
